apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intellmeet.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "intellmeet.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.server.port | quote }}
  NODE_ENV: {{ .Values.env.nodeEnv | quote }}
  CLIENT_URL: {{ .Values.env.clientUrl | quote }}
  MONGO_URI: mongodb://{{ include "intellmeet.fullname" . }}-mongodb:27017/intellmeet
  REDIS_URL: redis://{{ include "intellmeet.fullname" . }}-redis:6379
