apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intellmeet.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "intellmeet.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_ACCESS_SECRET: {{ .Values.secrets.jwtAccessSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  SENTRY_DSN: {{ .Values.secrets.sentryDsn | quote }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.secrets.cloudinaryCloudName | quote }}
  CLOUDINARY_API_KEY: {{ .Values.secrets.cloudinaryApiKey | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.secrets.cloudinaryApiSecret | quote }}
